live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutCirc"
color = "0x464d6a"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x434758"          # Negro
blue = "0x9c6aff"           # Azul morado claro
cyan = "0xa3b3ff"           # Cian morado
green = "0xddb3ff"          # Verde morado
magenta = "0xe1acff"        # Magenta
red = "0xff8b92"            # Rojo
white = "0xffffff"          # Blanco
yellow = "0xffe585"         # Amarillo

[colors.normal]
black = "0x292d3e"          # Negro
blue = "0x7a4b8c"           # Azul morado oscuro
cyan = "0x8a6bbf"           # Cian morado oscuro
green = "0xc3a1d6"          # Verde morado claro
magenta = "0x9b59b6"        # Magenta morado
red = "0xf07178"            # Rojo
white = "0xd0d0d0"          # Gris claro
yellow = "0xffcb6b"         # Amarillo

[colors.primary]
background = "#050000"
foreground = "0xd0d0d0"

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12

[font.bold]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 500
multiplier = 1

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
